---
- name: Install Docker and Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      shell: >
        curl -sL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: 'a+x'

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade existing packages
      apt:
        upgrade: yes

    - name: Display Docker status
      debug:
        var: docker_status.rc

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/docker-compose.yml

    - name: Execute Docker Compose
      command: sudo docker-compose up -d
      args:
        chdir: /home/
      become: yes

    - name: Create new Volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always